DROP TABLE playlist_shares;
DROP TABLE playlist_songs;
DROP TABLE playlists;
DROP TABLE music;
DROP TABLE users;
DROP TABLE user_friendship;
DROP TABLE play_log;
DROP TABLE liked_songs;
DROP TABLE notifications;
